```mermaid
mindmap
  root((Governança GAPD))
    Reunião 15/02/2024
      Participantes
        Conselho
          Marcelo O. Paro
          Arthur Villas Bôas
          Ana Lúcia Paro V. B.
          Alírio G. Pereira
          Aline Paro
          Luis Jaca
          Roni Chittoni
          Matheus Cônsoli
        Gestores
          Fernanda Civiero
          Hélcio
          Vinicius Pavani
      Pautas Principais
        1. Orçamento
          Apresentação do Projeto de Melhoria
          Estrutura de Planilhas Intermediárias (por departamento)
          Padronização de Formatos e Fórmulas
          Consolidação de Informações
          Aprovação do Layout de Acompanhamento Mensal (imagem)
        2. Endividamento
          Gestão Estratégica (R$ 240-250 milhões)
          Custos e Custeio (R$ 150 milhões)
          Caixa Positivo (R$ 35 milhões)
          Taxas de Juros Competitivas (9,75% vs. 14-15%)
        3. Guindances Financeiras (Safra 2024/25)
          Limite de Dívida Bruta (R$ 400 milhões)
          Dívida Líquida/EBITDA (2,5 - 2,7)
          Dívida para Expansão/EBITDA (máx. 3,5)
          Tax Shield (R$ 150 milhões - contas de acionistas)
          Exposição Cambial (US$ 15 milhões, incluindo US$ 5 milhões em euros)
        4. Apresentação AITHER
          Setor de Etanol e Açúcar
          Competitividade (etanol de milho x cana)
          Dinâmica do Mercado de Milho
          Sustentabilidade
          Desafios Logísticos e de Custo
          Inovação e Eficiência Operacional
          Tendências de Consumo e Preços
          Estimativas ATR (R$ 1,15)
        5. Estratégias de Comercialização (ATR)
           Disponibilidade de Cana: 600k ton
           Hedge: 178k ton (Preço médio: R$1.11)
           Hedgar: 420k ton em ritmo ajustado, buscando alcançar o preço médio de R$1,15
           Preço atingindo R$1,15: Vender 100k ton
        6. Atualização SOJA
          Preço Médio de Vendas: R$ 118,48 (183k scs)
          Gestão de Armazenagem (espaço em silo, margem de 20 dias)
      Atividades Abertas
        Jurídico
            Documento de Contas PF (aplicações financeiras) - AVB (Março/24)
            ICMS de MG para pecuária (pareceres) - AVB (Abril/24)
        Financeiro
          Demonstrativo de Ganhos Financeiros - AVB (Fevereiro/23)
        Comercial (MOP)
          Compartilhamento de Planilha de Vendas de Soja (cópia para Vinicius)
      Anexos
        Financeiros
          Acompanhamento_Endividamento NOVO.xlsx
          BASE ORÇAMENTO GAPD_Cria_2022.xlsx
          Caixa_Extra_Gestao Recurso.xlsx
          Cópia de Despesa Financeira Orçada_23_24.xlsx
          ENDIVIDAMENTO BANCO.pdf
          ENDIVIDAMENTO COM TAXAS.pdf
          FINANCIAMENTOS PJ SAFRA 24_25.pdf
          Investimentos_GAPD_Análise Inicial_2024_AJUSTES.xlsx
          Variação_Estoques_23_24.xlsx
          Viabilidade_Silo_TO.xlsx
        Operacionais
          Caminhões Próprios x Terceiros - 23-24.xlsx
        Apresentações
            Rastreabilidade do orçamento empresarial.pptx
            Riscos para precificação do Consecana - AITHER.pdf
        Outros
            NCG_GAPD.xlsx
            Intermediárias (folder)
      Assinaturas
```