avaliacao:
  pessoa_avaliada:
    identificador_pergunta: "Sua relacao com {{nome}} e como:"

competencias:
    - nome: Desenvolvimento de Pessoas 
      descricao: >
        Planeja e apoia o desenvolvimento das habilidades de todas as pessoas de sua equipe para que possam atender aos objetivos atuais e futuros de seus PAs. A pessoa demonstra essa competência: 1. Atribuindo responsabilidades e tarefas à sua equipe de acordo com suas habilidades, reconhecendo e valorizando os pontos fortes individuais; 2. Trabalhando com as pessoas de sua equipe para desenvolver seus pontos fortes, ajudá-las a gerenciar suas fraquezas, entender a necessidade prática de melhoria individual e definir metas de treinamento específicas; 3. Reconhecendo conquistas individuais e coletivas e promovendo um clima de autoconfiança por meio do bom uso do feedback; 4. Garantindo que oportunidades de treinamento estejam disponíveis e ajudando as pessoas de sua equipe a superar barreiras à aprendizagem.
      perguntas:
        objetivas:
          - "Com que frequencia o seu gestor esclarece as expectativas de comportamento, conhecimento e habilidades de todos integrantes da equipe, incluindo voce (pontos fortes e pontos fracos)?"
          - "Com que frequencia o seu gestor da instrucoes e modelos positivos para desenvolver as habilidades de todos os integrantes da sua equipe, incluindo voce (pontos fortes)?"
          - "Com que frequencia o seu gestor da feedback positivo e apropriado sobre o desempenho de todos os integrantes da sua equipe, incluindo voce?"
          - "Com que frequencia o seu gestor oferece suporte aos esforcos e progressos de todos os integrantes da sua equipe, incluindo voce (feedback)?"
          - "Com que frequencia o seu gestor faz com que todos os integrantes da sua equipe, incluindo voce, se sentirem valorizados e respeitados?"
          - "Com que frequencia o seu gestor ensina novos procedimentos e tarefas para todos os integrantes da sua equipe, incluindo voce?"
          - "Com que frequencia o seu gestor determina e esclarece o nivel de orientacao necessario para que cada membro da sua equipe, incluindo voce, consiga realizar bem as suas tarefas?"
          - "Com que frequencia o seu gestor procura saber e ouve as preocupacoes de todos os integrantes da sua equipe, incluindo voce, sobre desenvolvimento profissional?"
          - "Com que frequencia o seu gestor envolve a equipe na resolucao de problemas e processos de melhoria, reforcando o metodo PDCA?"
          - "Com que frequencia o seu gestor demonstra abordagens eficazes de resolucao de problemas, utilizando o metodo PDCA?"
        subjetivas:
          - "Coisas para melhorar sobre Desenvolvimento de Pessoas"
          - "Coisas para manter sobre Desenvolvimento de Pessoas"
      avaliadores:
        - liderado
        - autoavaliacao

    - nome: Trabalho em equipe
      descricao: >
        Participa ativamente como membro da equipe e ajuda a mobilizar o grupo para alcançar metas; demonstra compromisso pessoal com o grupo. A pessoa demonstra essa competência: 1. Fornecendo e compartilhando sugestões, orientações, informações importantes ou relevantes para o grupo; 2. Demonstrando "bom espírito de equipe" (empatia, respeito, acolhimento), agindo dentro das expectativas formais ou informais do grupo; 3. Ajudando nos esforços coletivos para obter recursos compatíveis com as metas da equipe ou para remover obstáculos; 4. Incentivando a equipe (de maneira adequada ao seu nível) a desenvolver e manter um nível claro de compromisso e direção alinhado com a Cultura de Excelência do GAPD.
      perguntas:
        objetivas:
          - "Com que frequencia o seu colega gestor demonstra a real intencao de estabelecer relacoes de confianca com outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de resolver conflitos de forma colaborativa com outros gestores, incluindo voce?" 
          - "Com que frequencia o seu colega gestor demonstra a real intencao de entender e levar em conta as perspectivas de outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de se coordenar com outros gestores para alcancar metas organizacionais?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao em dar e, principalmente, receber feedback de outros gestores de forma aberta e construtiva?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de apoiar as decisoes e acoes de outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de compartilhar experiencias e aprendizados com outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra humildade e abertura para aprender com outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de celebrar conquistas coletivas com outros gestores, incluindo voce?"
          - "Com que frequencia o seu colega gestor demonstra a real intencao de definir responsabilidades e papeis de forma clara ao trabalhar com outros gestores (gestao de processos)?"
        subjetivas:
          - "Coisas para melhorar sobre Trabalho em equipe" 
          - "Coisas para manter sobre Trabalho em equipe"
      avaliadores:
        - colega gestor
        - autoavaliacao

    - nome: Planejamento & Organizacao
      descricao: >
        Desenvolve planos de trabalho para si e para os outros (se for líder/gerente), garantindo que o trabalho seja concluído de forma eficiente; reconhece e diferencia o que é prioridade em relação ao total de tarefas. A pessoa demonstra essa competência: 1. Distinguindo as tarefas mais importantes das demais tarefas mundanas e equilibrando essas prioridades com prazos e recursos disponíveis para si e para sua equipe (se for líder/gerente); 2. Determinando os requisitos das tarefas, dividindo-as em partes menores, alocando os recursos e esforços necessários e coordenando suas iniciativas com as de outras pessoas (internas ou externas); 3. Alocando tempo adequado para completar seu próprio trabalho e o de outros (se for líder/gerente), evitando conflitos de agendamento, planejando e aderindo a cronogramas de forma eficiente; 4. Revisando e ajustando o plano de trabalho inicial, mantendo-o atualizado e adaptando-o a circunstâncias imprevistas; organizando com antecedência as ferramentas, equipamentos ou instrumentos necessários para realizar seu trabalho.
      perguntas:
        objetivas:
          - "Com que frequencia o gestor demonstra a habilidade em priorizar suas atividades, focando no que e mais importante (20/80)?"
          - "Com que frequencia o gestor demonstra a habilidade em determinar claramente as tarefas e recursos necessarios para realizar seu trabalho e de sua equipe?"
          - "Com que frequencia o gestor demonstra a habilidade em estabelecer cronogramas e prazos realistas para a entrega de resultados/conclusao de trabalho?"
          - "Com que frequencia o gestor demonstra a capacidade em aproveitar da melhor forma os recursos disponiveis (pessoas, equipamentos, ferramentas etc.) para realizar seu trabalho (20/80)?"
          - "Com que frequencia o gestor demonstra a habilidade em evitar distracoes e permanecer focado nas atividades prioritarias (20/80)?"
          - "Com que frequencia o gestor demonstra a habilidade em planejar e organizar seu proprio trabalho com autonomia?"
          - "Com que frequencia o gestor demonstra a habilidade em gerenciar o uso do tempo e dos recursos financeiros disponiveis corretamente diante das tarefas prioritarias?" 
          - "Com que frequencia o gestor demonstra a habilidade em coordenar suas atividades com as de outras areas/equipes/unidades para entregar resultados?"
          - "Com que frequencia o gestor demonstra saber quem sao os seus colegas especialistas que podem ajuda-lo a resolver problemas especificos (pontos fortes)?"
          - "Com que frequencia o gestor demonstra a habilidade de aconselhar sua equipe sobre prioridades e organizacao do trabalho (20/80)?"
        subjetivas:
          - "Coisas para melhorar sobre Planejamento & Organizacao"
          - "Coisas para manter sobre Planejamento & Organizacao"
      avaliadores:
        - diretor
        - autoavaliacao

    - nome: Orientacao para resultados
      descricao: >
        Consistentemente entrega os resultados esperados de sua posição (conforme descrito em seu PA); foca esforços na execução de objetivos para atendê-los ou superá-los, dentro dos prazos e condições. A pessoa demonstra essa competência: 1. Aceitando e resolvendo os objetivos definidos para seu PA; 2. Mantendo o compromisso com as metas de seu PA/área diante de obstáculos e dificuldades; 3. Encontrando ou criando maneiras de medir seus resultados em relação às metas descritas para seu PA/área; 4. Tendo um senso de urgência (equilibrado, adequado ao seu nível) para resolver problemas e concluir o trabalho; 5. Identificando e priorizando as tarefas mais importantes sobre as menos importantes e respondendo de forma eficiente, mesmo em momentos de maior pressão; 6. Incentivando a participação efetiva dos colegas em sua área para atingir metas.
      perguntas:
        objetivas:
          - "Com que frequencia o gestor demonstra a capacidade de identificar oportunidades para realizar trabalho de alto impacto em resultados de excelencia, alinhado com o seu PA?" 
          - "Com que frequencia o gestor demonstra a capacidade de estabelecer metas ambiciosas de sucesso da sua posicao (PA), relacionadas com as metas do GAPD e de realizacao pessoal?"
          - "Com que frequencia o gestor demonstra a capacidade de trabalhar com energia e vigor constantes para alcancar metas desafiadoras?"
          - "Com que frequencia o gestor demonstra a capacidade de assumir tarefas adicionais quando necessario, mesmo que nao seja responsabilidade direta dele/a?"
          - "Com que frequencia o gestor demonstra a capacidade de permanecer focado e evitar distracoes para concluir iniciativas importantes no prazo?"
          - "Com que frequencia o gestor demonstra a capacidade de acompanhar o progresso das atividades dele/a e realizar \"correcoes de rota\" com agilidade, quando necessario?"
          - "Com que frequencia o gestor demonstra senso de urgencia e determinacao para levar as questoes a conclusao?"
          - "Com que frequencia o gestor demonstra seu nivel de satisfacao ao alcancar metas desafiadoras?"
          - "Com que frequencia o gestor demonstra a capacidade de priorizar atividades de acordo com o impacto para obtencao do resultado de excelencia?"
          - "Com que frequencia o gestor demonstra autodisciplina e foco para entregar resultados esperados?"
        subjetivas:
          - "Coisas para melhorar sobre Orientacao para resultados"
          - "Coisas para manter sobre Orientacao para resultados"
      avaliadores:
        - diretor
        - autoavaliacao

    - nome: Conhecimento tecnico
      descricao: >
        Alcança um nível de conhecimento técnico e profissional (a expertise) e habilidade (o know-how) compatível com sua posição; mantém-se atualizado com os desenvolvimentos em sua área de especialização. A pessoa demonstra essa competência: 1. Conhecendo e usando os componentes técnicos relacionados ao seu trabalho/PA (por exemplo, conhecimento de legislação, técnicas de execução/operação padronizadas, funcionalidades dos sistemas de gestão, técnicas de planejamento, etc.); 2. Conseguindo realizar tarefas complexas (adequadas ao seu nível) de forma segura, sem orientação ou instrução; 3. Desenvolvendo soluções ou combinando abordagens técnicas tradicionais (adequadas ao seu nível) para resolver problemas novos e/ou complexos que não podem ser resolvidos por métodos convencionais; 4. Mantendo-se atualizado sobre inovações, novas tendências e/ou novos conhecimentos em sua área.
      perguntas:
        objetivas:
          - "Com que frequencia o gestor demonstra o seu conhecimento sobre seu departamento/atividade e funcao atual (PA)?"
          - "Com que frequencia o gestor demonstra o seu conhecimento sobre regras, processos e praticas necessarias para realizar trabalho dele?"
          - "Com que frequencia o gestor demonstra interesse por manter-se atualizado sobre novas tendencias e melhores praticas em sua area?"
          - "Com que frequencia o gestor demonstra o seu conhecimento sobre as ferramentas e sistemas necessarios para realizar seu trabalho de forma eficiente?"
          - "Com que frequencia o gestor demonstra sua capacidade de compreender os aspectos e habilidades necessarios para obter resultados de excelencia na funcao dele?"
          - "Com que frequencia o gestor demonstra sua real intencao em aplicar seus conhecimentos tecnicos para resolver problemas e desenvolver solucoes efetivas?"
          - "Com que frequencia o gestor demonstra sua real intencao em manter seus conhecimentos atualizados e em desenvolvimento continuo?"
          - "Com que frequencia o gestor demonstra habilidade em analisar situacoes, levando em conta os possiveis impactos nas areas de outros gestores, com base em seu conhecimento?"
          - "Com que frequencia o gestor demonstra sua real intencao de compartilhar seus conhecimentos para desenvolver a equipe?"
          - "Com que frequencia o gestor demonstra sua real intencao em aumentar o nivel de conhecimento tecnico e profissional para o desempenho eficiente de seu trabalho?"
        subjetivas:
         - "Coisas para melhorar sobre Conhecimento tecnico"
         - "Coisas para manter sobre Conhecimento tecnico"
      avaliadores:
       - diretor
       - autoavaliacao

    - nome: Otimizacao de recursos
      descricao: >
       Gerencia de forma eficiente os recursos à sua disposição, buscando otimizar os processos de trabalho e reduzir custos. A pessoa demonstra essa competência: 1. Estando atenta à implementação de procedimentos e ferramentas (80/20, PDCA) visando o melhor aproveitamento dos recursos de trabalho à sua disposição; 2. Implementando procedimentos, adequados ao seu nível, para reduzir desperdícios e custos desnecessários; 3. Propondo medidas para otimizar e simplificar processos ou procedimentos para melhorar a produtividade e a gestão de custos; 4. Liderando seus funcionários na busca contínua de redução de custos e resultados de "excelência" (se for líder/gerente); 5. Instruindo os funcionários sobre o uso adequado dos recursos disponíveis (equipamentos, instrumentos, etc.) (se for líder/gerente).
      perguntas:
       objetivas:
         - "Com que frequencia o gestor implementa procedimentos e ferramentas para melhor aproveitamento dos recursos disponiveis?"
         - "Com que frequencia o gestor implementa procedimentos para reducao de desperdicios e custos desnecessarios (gestao de processos)?"
         - "Com que frequencia o gestor propoe medidas para racionalizacao e simplificacao de processos, visando melhoria da produtividade e gestao de custos (gestao de processos)?"
         - "Com que frequencia o gestor orienta sua equipe para a busca continua de reducao de custos e excelencia?"
         - "Com que frequencia o gestor instrui sua equipe sobre o bom uso de recursos disponiveis, como equipamentos e instrumentos?"
         - "Com que frequencia o gestor foca na otimizacao dos recursos financeiros da area/GAPD (orcados versus realizado)?"
         - "Com que frequencia o gestor demonstra interesse em eliminar desperdicios e retrabalhos nos processos (gestao de processos)?"
         - "Com que frequencia o gestor prioriza iniciativas de acordo com o impacto na reducao de custos?"
         - "Com que frequencia o gestor foca em executar processos e solucoes de baixo custo, sem comprometer a qualidade dos resultados (cultura de excelencia)?" 
         - "Com que frequencia o gestor maximiza resultados com os recursos disponiveis?"
       subjetivas:
         - "Coisas para melhorar sobre Otimizacao de recursos"
         - "Coisas para manter sobre Otimizacao de recursos"
      avaliadores:
       - diretor
       - autoavaliacao

categorias_avaliador:
 campo_identificacao: "Tags"
 categorias:
   - "diretor"
   - "colega gestor"
   - "liderado"
   - "autoavaliacao"

xlsx_processing:
  discard_columns:
  - "#"
  - "Start Date (UTC)"
  - "Stage Date (UTC)"
  - "Submit Date (UTC)"
  - "Network ID"
  remove_accentuation: true

heatmap_formatting:
  cmap: "coolwarm_r"
  cbar: true
  cbar_kws:
    ticks:
      - 1
      - 2
      - 3
      - 4
      - 5
  vmin: 1
  vmax: 5
  index_labels: 
    - "Q1"
    - "Q2"
    - "Q3"
    - "Q4"
    - "Q5"
    - "Q6"
    - "Q7"
    - "Q8"
    - "Q9"
    - "Q10"
  xlabel: "questions"
  ylabel: "responses"
  apply_numeric_conversion: true
  grid:
    color: "gray"
    linestyle: "-"
    linewidth: 0.5
  highlight_autoavaliacao:
    enabled: true
    color: "red"
    linestyle: "dashed"
    linewidth: 1.5
  figsize: [10, 8]
  title_template: "Heatmap de {competencia} - {pessoa}"

radar_formatting:
  figsize: [6, 6]
  fill_color: "blue"
  fill_alpha: 0.25
  line_color: "blue"
  line_width: 2
  title_template: "Grafico Radar de Competencias - {pessoa}"