file_path: "/home/roni-chittoni/ProjectsHub/GAPD/core/laboratorio/data/raw/responses/responses.csv"
stacked_chart_variables:
  - "PISOTEIO"
  - "DANOS"
  - "FOCO"
violin_plot_columns:
  - "PISOTEIO"
  - "DANOS"
  - "FOCO"
output_folder: "/home/roni-chittoni/ProjectsHub/GAPD/core/laboratorio/data/processed/responses/monitor_colheita"
unidade: "Canada"
periodo: "0110-2810"

# Títulos e Eixos dos Gráficos
stacked_chart_titles:
  PISOTEIO: "Pisoteio - Vistorias/Notas por Líder"
  DANOS: "Danos - Vistorias/Notas por Líder"
  FOCO: "Foco - Vistorias/Notas por Líder"
violin_plot_title: "Notas de Vistoria"
violin_plot_x_labels: ["muito ruim", "ruim", "médio", "bom", "muito bom"]
violin_plot_x_axis_label: "Notas"
violin_plot_y_axis_label: ""

# Configurações de Formatação de Excel
excel_columns_to_drop:
  - "#"
  - "Response Type"
  - "Start Date (UTC)"
  - "Stage Date (UTC)"
  - "Network ID"
  - "Tags"
excel_conditional_formatting_columns:
  - "PISOTEIO"
  - "DANOS"
  - "FOCO"
